apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise-chart
  labels:
    app: devops-exercise
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-exercise
  template:
    metadata:
      labels:
        app: devops-exercise
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
