apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-exercise
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
